### ISSUE TITLE
No enforcing of PDF inline display in contemporary Chrome v122.x

### ISSUE THREAD

**Issue by porg** [semenko/chrome-force-pdf-inline#6]
- Good feature idea!
- Thanks for providing that extension!
- Sadly as of 2024-03-21 the extension in it latest released version 2016.4.7 is not working anymore in the current Chrome 122.0.6261.129.
  - Tried it on https://www.bmf.gv.at/services/publikationen/das-steuerbuch.html where the PDFs use "Content-Disposition: attachment" and enforcing PDF inline display fails, instead the PDFs just trigger a download.

**Comment by semenko** [comment]
Hey, thanks for looking at this! It's been a **long** time since I've updated this, clearly.

I wonder content-type injection has been deprecated or otherwise failed in more recent versions of Chrome -- it's also possible some pre-fetched content bypasses the extension.

**Comment by semenko** [comment]
Partially fixed in the new version for Manifest v3 (currently undergoing Chrome webstore review).

This should correctly match the header (e.g., this url: https://www.bmf.gv.at/dam/jcr:b211cc2d-8994-4783-9230-22c3c8a2d9a0/230213_Steuerbuch2023_EN_BF.pdf).

**However**, the .html page above forces PDFs to download by a different mechanism: the `<a>` has the rarely used **download attribute** that we can't overwrite:

![image](https://github.com/user-attachments/assets/01655fcf-1509-4156-93b2-b4dcde920c8d)

**Comment by porg** [comment]
Thank for the info.

I'd expect/hope from a plugin that has "force" in its name that it can override any contradicting instructions, be it:
- HTTP header `Content-Disposition: attachment`.
- HTML `<a>` element with a `download` flag present. Btw, thanks for the info, did not know about this!
  - Why can you not override this behavior?
  - If not with the given mechanisms for Chrome extensions, would it be possible to intervene "lower" as in manipulating the DOM and removing any `download` attributes encountered in `<a>` elements if having a `href="/with/a/filepath/ending-in.pdf"`?

To not necessitate that your extension reads all website data all the time, for that DOM manipulation to remove `<a download>` flags, maybe you could offer a context menu entry "Open PDF inline" when right clicking links, whose destination ends in `*.pdf`? 
- Then opens a new tab where it directly requests the URL (hence bypasses the `<a download>` flag) and any possible HTTP header `Content-Disposition: attachment` is circumvented by your mechanism already in place.
- What do you say?

**Comment by semenko** [comment]
Worth considering! The options are a bit limited & under more scrutiny with the latest Manifest v3 changes to Chrome, alas.

(If you right-click & open in new tab, the `download` element of `<a>` is ignored.)

**Comment by porg** [comment]
1. Right-clicking & opening in new tab by Chrome's native behavior disables the `download` attribute of `<a>`
2. Your extension handles the potential HTTP header in the new tab.

So we are feature complete for all use cases!

No need to develop a custom context menu entry! Looking forward to test out the extension as soon as it is through the release procedure! 

Will report whether the described scenario works as expected.
